server:
  port: 8080

spring:
  flyway:
    baselineOnMigrate: true
    check-location: true
    locations: classpath:db/migration
    schemas: ymal
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

app:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/YMAL?useSSL=false
    username: root
    password: Monday2019!
