server:
  servlet:
    context-path: /api
  port: 8080

spring:
  flyway:
    baselineOnMigrate: true
    check-location: true
    locations: classpath:db/migration
    schemas: ymal
    enabled: true
    validateOnMigrate: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: ymal

app:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/YMAL?useSSL=false
    username: root

logging:
  level:
    root: DEBUG
