CREATE TABLE IF NOT EXISTS ymal_product (
    id INTEGER PRIMARY KEY NOT NULL,
    name VARCHAR(250) NOT NULL,
    designer VARCHAR(250) NOT NULL,
    colour VARCHAR(250) NOT NULL,
    category VARCHAR(250) NOT NULL
);